create or alter view WSZYSTKO AS
select	distinct
		g.id as Gmina_ID,
		g.Nazwa as Gmina_Nazwa,
		g.Rodzaj as Gmina_Rodzaj,
		g.StartDate as Gmina_StartDate,
		g.EndDate as Gmina_EndDate,
		g.StartDateVerified as Gmina_StartDateVerified,
		g.EndDateVerified as Gmina_EndDateVerified,
		g.CzyDataPowstania as Gmina_CzyDataPowstania,
		g.opis as Gmina_Opis,
		gp.IDPowiat as GminaPowiat_IDPowiat,
		gp.StartDatePowiat as GminaPowiat_StartDatePowiat,
		gp.IDGmina as GminaPowiat_IDGmina,
		gp.StartDateGmina as GminaPowiat_StartDateGmina,
		gp.StartDate as GminaPowiat_StartDate,
		gp.EndDate as GminaPowiat_EndDate,
		gp.StartDateVerified as GminaPowiat_StartDateVerified,
		gp.EndDateVerified as GminaPowiat_EndDateVerified,
		gp.Opis as GminaPowiat_Opis,
		gw.IDGmina as GminaWojewodztwo_IDGmina, 
		gw.StartDateGmina as GminaWojewodztwo_StartDateGmina, 
		gw.IDWojewodztwo as GminaWojewodztwo_IDWojewodztow,
		gw.StartDateWojewodztwo as GminaWojewodztwo_StartDateWojewodztwo,
		gw.StartDate as GminaWojewodztwo_StartDate,
		gw.EndDate as GminaWojewodztwo_EndDate,
		gw.StartDateVerified as GminaWojewodztwo_StartDateVerified,
		gw.EndDateVerified as GminaWojewodztwo_EndDateVerifief,
		gw.Opis as GminaWojewodztwo_Opis,
		p.ID as Powiat_ID,
		p.Nazwa as Powiat_Nazwa,
		p.Rodzaj as Powiat_Rodzaj,
		p.StartDate as Powiat_StartDate,
		p.EndDate as Powiat_EndDate,
		p.StartDateVerified as Powiat_StartDateVerified,
		p.EndDateVerified as Powiat_EndDateVerified,
		p.CzyDataPowstania as Powiat_CzyDataPowstania,
		p.Opis as Powiat_Opis,
		pw.IDPowiat as PowiatWojewodztwo_IDPowiat,
		pw.StartDatePowiat as PowiatWojewodztwo_StartDatePowiat,
		pw.IDWojewodztwo as PowiatWojewodztwo_IDWojewodztwo,
		pw.StartDateWojewodztwo as PowiatWojewodztwo_StartDateWojewodztwo,
		pw.StartDate as PowiatWojewodztwo_StartDate,
		pw.EndDate as PowiatWojewodztwo_EndDate,
		pw.StartDateVerified as PowiatWojewodztwo_StartDateVerified,
		pw.EndDateVerified as PowiatWojewodztwo_EndDateVerified,
		pw.Opis as PowiatWojewodztwo_Opis,
		w.id as Wojewodztwo_ID,
		w.Nazwa as Wojewodztwo_Nazwa,
		w.Rodzaj as Wojewodztwo_Rodzaj,
		w.StartDate as Wojewodztwo_StartDate,
		w.EndDate as Wojewodztwo_EndDate,
		w.StartDateVerified as Wojewodztwo_StartDateVerified,
		w.EndDateVerified as Wojewodztwo_EndDateVerified,
		w.CzyDataPowstania as Wojewodztwo_CzyDataPowstania,
		w.Opis as Wojewodztwo_Opis

from Wojewodztwo w
left join PowiatWojewodztwo pw on w.ID = pw.IDWojewodztwo and w.StartDate = pw.StartDateWojewodztwo
left join Powiat p on p.id = pw.IDPowiat and p.StartDate = pw.StartDatePowiat
left join GminaWojewodztwo gw on w.ID = gw.IDWojewodztwo and w.StartDate = gw.StartDateWojewodztwo
left join GminaPowiat gp on p.ID = gp.IDPowiat and p.StartDate = gp.StartDatePowiat
join gmina g on g.ID = gw.IDGmina and g.StartDate = gw.StartDateGmina or g.ID = gp.IDGmina and g.StartDate = gp.StartDateGmina